// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// src/app/layout.tsx
import "./globals.css";
import Navbar from "../components/Navbar";
import BlogStrip from "../components/BlogStrip";
import Footer from "../components/Footer";

export const metadata = {
  title: "My Portfolio",
  description: "Welcome to my portfolio website built with Next.js and Tailwind CSS.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative flex min-h-screen flex-col overflow-x-hidden bg-gradient-to-b from-slate-50 via-white to-indigo-50/40 text-gray-900 dark:from-slate-950 dark:via-gray-950 dark:to-indigo-950/20 dark:text-gray-100">
        {/* Global animated background */}
        <div
          aria-hidden
          className="pointer-events-none fixed inset-0 -z-10"
        >
          <div className="absolute -top-24 left-1/2 h-[28rem] w-[28rem] -translate-x-1/2 rounded-full bg-gradient-to-tr from-indigo-500/20 via-violet-500/20 to-fuchsia-500/20 blur-3xl animate-[gradientShift_14s_ease-in-out_infinite]" />
          <div className="absolute bottom-[-8rem] left-[-6rem] h-[22rem] w-[22rem] rounded-full bg-gradient-to-tr from-emerald-400/10 via-sky-400/10 to-indigo-400/10 blur-3xl animate-[floaty_12s_ease-in-out_infinite]" />
          <div className="absolute right-[-7rem] top-1/3 h-[24rem] w-[24rem] rounded-full bg-gradient-to-tr from-fuchsia-500/10 via-violet-500/10 to-indigo-500/10 blur-3xl animate-[floaty_16s_ease-in-out_infinite]" />
        </div>

        <Navbar />
        <main className="container mx-auto flex-grow p-4">{children}</main>
        <BlogStrip compact />
        <Footer />
      </body>
    </html>
  );
}
